# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(927, 492)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_2 = QtGui.QPushButton(self.frame_5)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 4, 1, 1, 1)
        self.filename_text = QtGui.QLineEdit(self.frame_5)
        self.filename_text.setMinimumSize(QtCore.QSize(450, 0))
        self.filename_text.setObjectName(_fromUtf8("filename_text"))
        self.gridLayout_2.addWidget(self.filename_text, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 3)
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.btnBrowse = QtGui.QPushButton(self.frame_5)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.gridLayout_2.addWidget(self.btnBrowse, 1, 1, 1, 1)
        self.dirname_text = QtGui.QLineEdit(self.frame_5)
        self.dirname_text.setObjectName(_fromUtf8("dirname_text"))
        self.gridLayout_2.addWidget(self.dirname_text, 4, 2, 1, 1)
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.btnBrowse.raise_()
        self.filename_text.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.dirname_text.raise_()
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.frame_4)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.container_selection = QtGui.QComboBox(self.frame_4)
        self.container_selection.setObjectName(_fromUtf8("container_selection"))
        self.container_selection.addItem(_fromUtf8(""))
        self.container_selection.addItem(_fromUtf8(""))
        self.container_selection.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.container_selection, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.frame_5.raise_()
        self.frame_5.raise_()
        self.frame_5.raise_()
        self.label.raise_()
        self.frame_5.raise_()
        self.frame_5.raise_()
        self.frame_5.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.container_selection.raise_()
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox = QtGui.QCheckBox(self.frame_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 0, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_3.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.frame_4.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.frame_4.raise_()
        self.label_6.raise_()
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(120, 40, 151, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 927, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_single_file = QtGui.QAction(MainWindow)
        self.actionOpen_single_file.setObjectName(_fromUtf8("actionOpen_single_file"))
        self.actionOpen_Directory_Batch = QtGui.QAction(MainWindow)
        self.actionOpen_Directory_Batch.setObjectName(_fromUtf8("actionOpen_Directory_Batch"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionOpen_single_file)
        self.menuFile.addAction(self.actionOpen_Directory_Batch)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FFV1 Transcoder v0.1 - 2016", None))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>DISABLED - All files are processed.</p></body></html>", None))
        self.pushButton_2.setText(_translate("MainWindow", "Select folder for MULTIPLE file transcodes", None))
        self.label_5.setText(_translate("MainWindow", "OR", None))
        self.label_3.setText(_translate("MainWindow", "1.a", None))
        self.label_2.setText(_translate("MainWindow", "Step 1 : Choose input - Either a single file or an entire folder", None))
        self.label_4.setText(_translate("MainWindow", "1.b", None))
        self.btnBrowse.setToolTip(_translate("MainWindow", "<html><head/><body><p>One file is processed</p></body></html>", None))
        self.btnBrowse.setText(_translate("MainWindow", "Select file for single transcode", None))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>OPTIONAL - Sidecars are generated by default</p></body></html>", None))
        self.pushButton_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.pushButton_3.setText(_translate("MainWindow", "Select destination folder for transcoded file(s)", None))
        self.lineEdit.setText(_translate("MainWindow", "Select Container: (MKV by default)", None))
        self.container_selection.setItemText(0, _translate("MainWindow", ".mkv", None))
        self.container_selection.setItemText(1, _translate("MainWindow", ".mov", None))
        self.container_selection.setItemText(2, _translate("MainWindow", ".avi", None))
        self.label.setText(_translate("MainWindow", "Step 2: Output Options - Not mandatory. Sidecar MKV files are enabled by default", None))
        self.checkBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>This disables lossless verification and the generate of frame level checksums. Disable at your own risk.</p></body></html>", None))
        self.checkBox.setText(_translate("MainWindow", "Disable Framemd5 Lossless Verification (Speed Increase - NOT RECOMMENDED)", None))
        self.checkBox_2.setText(_translate("MainWindow", "Generate whole file md5 manifest", None))
        self.label_6.setText(_translate("MainWindow", "General Options", None))
        self.pushButton.setText(_translate("MainWindow", "Encode", None))
        self.label_7.setText(_translate("MainWindow", "Final Step", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_single_file.setText(_translate("MainWindow", "Open Single File", None))
        self.actionOpen_Directory_Batch.setText(_translate("MainWindow", "Open Directory (Batch)", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

